import './globals.css';

import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';

import { Footer, Header } from '@/components';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bússola da Gestão',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${rubik.variable} ${inter.variable} antialiased`}>
        <div className="grid min-h-dvh grid-rows-[auto_1fr_auto]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
